Create geolocated-bar-chart-maps.md
NCSU-Libraries/data-science-cookbook pull request #24
Opened 2021-05-27 12:41 UTC by mikenutt

This is the original tutorial from @kmricha4. Previously named Tableau.Tutorial.md https://github.com/NCSU-Libraries/data-science-cookbook/files/6385611/Tableau.Tutorial.md

2021-05-27 15:19 UTC, WaltGurley requested changes
I fixed some typos (I may have missed some) and issues with the Markdown formatting in this document. There are a few additional issues:
- Should the attribution be "Written by the Data Visualization Lab"
- If I understand correctly, there should be an accompanying dataset.
- There are references to images throughout the instructions (e.g., [Insert Image 1]) that are not included
- In the "calculate field" sections, the syntax includes weird blanks (e.g., LEFT ("██████████"...). Is this correctly formatted?

2021-05-27 17:28 UTC, mikenutt commented
@WaltGurley Thanks for the fixes. 
- I am making another commit with a revised attribution credit. Is that the best way to make those changes in the pull request workflow? Would need to figure out if the MIT license applies here too. 
- Yes, the whole tutorial kind of hinges on those weird calculated field blanks as a workaround for making the bars. In the new credit statement, I mentioned [this page](https://www.dataplusscience.com/BarChartMaps.html) which describes how this method has been developed over time.
- You are right there's a spreadsheet missing. I thought @kmricha4 was going to paste a table into the markdown. I'll have to see if I can get in touch with her or else recreate it.
- So yes, there is still a fair amount of work to be done on this w/r/t images and .xls but I was trying to get it into the repo to capture the current work state until I could devote more time to it. May also want to delegate that work to Consultants, so your concerns could be turned into GitHub issues to assign.

2021-07-02 13:41 UTC, mikenutt commented
@WaltGurley I made some improvements in the areas you mentioned. Could you go ahead and approving this pull request to get the main content .md in place? I could convert outstanding problems discussed here to issues.  I will change the bad URL in the /Tableau folder. Anything else you'd want to see before merging?

2021-07-06 13:18 UTC, WaltGurley approved these changes

2021-07-06 13:18 UTC, merged